- name: Install snmpd
  hosts: all
  become: true
  become_user: root
  vars:
  tasks:

    - name: Install snmpd package
      yum: name=net-snmp state=latest

    - name: Enable snmpd service
      service: name=snmpd enabled=yes
      notify: Restart snmpd

  handlers:
    - name: Restart snmpd
      action: service name=snmpd state=restarted