- name: delete default snmpd config
  hosts: all
  become: true
  become_user: root
  vars:
  tasks:
  
      - name: create smpd.conf file
        file:
          path: /etc/snmp/snmpd.conf
          state: touch 
  
      - name:  configure snmpd in blockinfile /etc/snmp/snmpd.conf
        blockinfile:
         dest: /etc/snmp/snmpd.conf
         block: |
          syslocation Server Room
          syscontact SysAdmin (devops@example.com)
          rocommunity snmp_secret_rocommunity