---
- name: game2048 reload iptables
  command: iptables-restore /etc/sysconfig/iptables
  when:
    # should be removed after releasing https://github.com/ansible/ansible/issues/66304
    - ansible_virtualization_type != "docker"
    - ansible_virtualization_type != "VirtualPC"
- name: game2048 reload ip6tables
  command: ip6tables-restore /etc/sysconfig/ip6tables
  when:
    # should be removed after releasing https://github.com/ansible/ansible/issues/66304
    - ansible_virtualization_type != "docker"
    - ansible_virtualization_type != "VirtualPC"
