---

- name: Install 2048
  hosts: all
  become: true
  become_user: root
  vars:
    community_string: 'public'
    iptables_allowed_ports:
      - {protocol: tcp, port: 80}
      - {protocol: tcp, port: 180}
      - {protocol: tcp, port: 443}
      - {protocol: udp, port: 1161}
#    iptables_filename : iptables
    user:
      login: deploy
      password_hash:
        "$6$NwI7op8FHR1VQta6$zuQXHtNtM/7SRQsf1./18WbBrHMq4mT88nWh67ThmlWcqyVX3\
        FBTY9uj/07tR9ViDEvjg6/bh0y3mSjeDQYe3."
      authorized_key:
        "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YV\
        r+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv\
        6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn\
        5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0\
        jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE9\
        8OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
  tasks:
    - name: Create admin user
      import_tasks: provision_users.yml
    - name: get snmp community_string
      template:
        src: snmp_template.j2
        dest: /etc/snmp/snmp.txt
    - name: Install snmpd package
      yum: name=net-snmp state=latest
    - name: Enable snmpd service
      service: name=snmpd enabled=yes
      notify: Restart snmpd
    - name: Configure iptables
      import_tasks: provision_iptables.yml
#    - name: reload iptables
#      service:
#        name: iptables
#        state: restarted
#      command: iptables-restore /etc/sysconfig/iptables
#      when: /etc/sysconfig/iptables is changed
  handlers:
    - name: Restart snmpd
      action: service name=snmpd state=restarted