---
secret_password: "{{ vault_secret_password }}"
common__enable_httpd: true
game2048__git_src: https://github.com/ultral/2048.git
game2048__git_dst: /var/www/html
common__iptables_allowed_ports:
  - {protocol: tcp, port: 80}
  - {protocol: tcp, port: 443}
  - {protocol: udp, port: 161}
users__super_admins:
  - login: deploy
    password_hash:
      "$6$NwI7op8FHR1VQta6$zuQXHtNtM/7SRQsf1./18WbBrHMq4mT88nWh67ThmlWcqyVX3FBTY9uj/07tR9ViDEvjg6/bh0y3mSjeDQYe3."
    email: dep@loy.me
  - login: deploy2
    email: dep@loy.com
