---
# DEFAULT_PRIVATE_ROLE_VARS=false ansible-playbook -i inventory.yml demo_ab.yml
# DEFAULT_PRIVATE_ROLE_VARS=true  ansible-playbook -i inventory.yml demo_ab.yml

- hosts: localhost
  roles:
    - role: role_a
    - role: role_b
  tasks:
    - debug:
        msg: play={{ msg }}
