---
- hosts: localhost
  roles:
    - role: example_plugins
  vars:
    admins:
      - login: login1
        email: dep@loy.me
      - login: login2
      - login: login3
        email: dep@loy.com
      - login: login4
  tasks:
    - name: print all acounts as is
      debug:
        msg: "{{ admins }}"
    - name: print all acounts without email
      debug:
        msg:
          "{% set out_list = [] %}\
          {% for user in admins %}\
          {% if not user.email is defined %}\
          {{ out_list.append(user.login) }}\
          {% endif %}\
          {% endfor %}\
          {{ out_list }}"
    - name: print all acounts without email via standard jinja2 filters
      debug:
        msg: >-
          {{ admins |
            selectattr('email', 'undefined') |
            map(attribute='login') |
            list }}
    - name: print all acounts without email via custom test plugin
      debug:
        msg: >-
          {{ admins |
            select('has_email') |
            map(attribute='login') |
            list }}
    - name: print all acounts without email via custom filter
      debug:
        msg: "{{ admins | users_without_email }}"
