---
- name: Install software
  package:
    name: "{{ common__software }}"
    state: present
  retries: 30
  delay: 5
  register: result
  until: result is not failed
- name: Configure iptables
  template:
    src: "{{ common__iptables_item }}.j2"
    dest: /etc/sysconfig/{{ common__iptables_item }}
    force: true
    # it's commented because github actions do not allow use ip6
    # https://github.com/actions/virtual-environments/issues/668
    # validate: /sbin/{{ common__iptables_item }}-restore --test %s
    mode: 0644
    owner: root
    group: root
  loop:
    - iptables
    - ip6tables
  loop_control:
    loop_var: common__iptables_item
  notify:
    - common - reload iptables
    - common - reload ip6tables
- name: Start and enable httpd
  systemd:
    name: httpd
    enabled: true
    state: started
    daemon_reload: true
  when:
    - common__enable_httpd
    - ansible_distribution == 'CentOS'
